services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    command: postgres -c log_statement=all
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
   postgres_data:

